import sec, { SecludedAdapter } from './adapter/index.js';
import sec_ws from './adapter/WebSocket.js';
Bot.adapter.push(sec.adapter);
logger.mark(`===============`);
logger.mark(`${logger.blue('[Secluded-Adapter]')} author Senior Horikawa ！！！`);
logger.mark(`${logger.blue('[Secluded-Adapter]')} version 0.0.1`);
logger.mark(`${logger.blue(`[Secluded-Adapter]`)} repository https://github.com/Lovely02Y/Secluded-Adapter`);
logger.mark(`===============`);
await sec_ws.load();
let apps = {};
apps[SecludedAdapter.name] = SecludedAdapter;
export { apps };
